language: php
php:
  - '7.4'

install:
  - travis_retry composer install --no-interaction --no-suggest
  -
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

# Testing the app, generating code coverage report
script:
  - vendor/bin/phpunit --coverage-clover coverage.xml

after_success:
# Submit coverage report to https://codecov.io
  - bash <(curl -s https://codecov.io/bash -t 912dd081-b99b-436c-9fcd-d95e8b64843f)

# Monitor only these branches
branches:
  only:
    - master
    - dev

# Use travis-ci web interface to delete the cache
cache:
  directories:
    - $HOME/.composer/cache
